version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecretpassword
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    ports:
      - "8080:80"  # Map to 8080 to avoid conflicts
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=your-onlyoffice-secret  # Match with backend
    volumes:
      - ./onlyoffice-data:/var/www/onlyoffice/Data
      - ./onlyoffice-logs:/var/log/onlyoffice

volumes:
  data:
  onlyoffice-data:
  onlyoffice-logs:
